Repository Onyxmoon/hsfl-master-ai-cloud-engineering, pull requests merged in 2023-11, with the labels that each got.

#62 Proxy refactor
  lib/router/router.go
  src/http-proxy-service/config/proxyConfig.yaml
  src/http-proxy-service/go.mod
  src/http-proxy-service/main.go
  src/http-proxy-service/proxy/default_manager.go
  src/http-proxy-service/proxy/manager.go
  src/http-proxy-service/proxy/proxyutils/ReadDefaultProxyManagerConfiguration.go
Labels: http-proxy-service

#66 docs: update architecture diagram
  README.assets/CE_Architecture_Prototype.svg
Labels: documentation

#67 Feature/docker test
  .github/workflows/docker-push-registry.yml
  .github/workflows/run-tests-http-proxy-service.yml
  .github/workflows/run-tests-product-service.yml
  .github/workflows/run-tests-shoppinglist-service.yml
  .github/workflows/run-tests-user-service.yml
  .github/workflows/run-tests-web-service.yml
  docker-compose.yml
  go.work
  lib/router/go.mod
  lib/router/go.sum
  src/http-proxy-service/Dockerfile
  src/http-proxy-service/README.md
  src/http-proxy-service/go.mod
  src/http-proxy-service/proxy/default_manager.go
  src/http-proxy-service/proxy/manager.go
  src/product-service/Dockerfile
  src/product-service/api/router/router.go
  src/product-service/go.mod
  src/product-service/products/default_controller_test.go
  src/shoppinglist-service/Dockerfile
  src/shoppinglist-service/api/router/router.go
  src/shoppinglist-service/go.mod
  src/user-service/Dockerfile
  src/user-service/api/router/router.go
  src/user-service/go.mod
  src/user-service/main.go
  src/web-service/Dockerfile
  src/web-service/api/router/router.go
  src/web-service/go.mod
Labels: enhancement, build

#68 build: fix docker push workflow
  .github/workflows/docker-push-registry.yml
Labels: build

#70 Feature/proxy docker config
  docker-compose.dev.yml
  docker-compose.yml
  src/http-proxy-service/Dockerfile
  src/http-proxy-service/main.go
Labels: build

#81 feat(user-service): configure main.go
  src/user-service/main.go
Labels: user-service

#93 fix(docker): add missing flag for build command in docker workflow
  .github/workflows/docker-push-registry.yml
  docker-compose.push.yml
Labels: bug, build

#91 Test/improve user service coverage
  README.md
  src/user-service/api/handler/login_test.go
  src/user-service/api/handler/register_test.go
  src/user-service/auth/jwt_token_generator_test.go
Labels: test, user-service

#92 feat(product-service): add getByEan for Products, update dependent files
  README.md
  src/product-service/api/router/router.go
  src/product-service/products/controller.go
  src/product-service/products/default_controller.go
  src/product-service/products/default_controller_test.go
  src/product-service/products/demo_repository.go
  src/product-service/products/demo_repository_test.go
  src/product-service/products/repository.go
Labels: web-service, product-service, frontend

#97 Feature/general refactor
  README.assets/CE_Architecture_Prototype.svg
  src/load-balancer-service/main.go
  src/load-balancer-service/orchestrator/orchestrator.go
Labels: cleanup

#98 refactor: fix docker workflow
  .github/workflows/docker-push-registry.yml
Labels: build
